services:
  - type: web
    name: bin-ai-hub
    env: python
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PORT
        value: 5000
